### PR TITLE
Add GehrmannWidget to project

### PR DESCRIPTION
**Pull request by thgehr**
My first contribution to FlutterBuddies.
Add my widget to the project.

### CODE REVIEW

**Comment by slovnicki** [comment]
Welcome @thgehr!

I see your `GehrmannWidget` only has "Example Widget" text. Is this intentional or you plan to implement something more to your Widget? (any additional changes you push to your fork will automatically sync with this PR).

**Comment by thgehr** [comment]
Hi @slovnicki ,

I am happy to be part of this organization. I'm a beginner in Flutter and in working on open source projects.
I just wanted to do my first PR to get used to the work flow.
I plan to implement more on my widget the next days.

Cheers,
Thomas

**Comment by slovnicki** [comment]
@thgehr Great!

Then you just push additional commits to your forked repo and it will be synced to this PR automatically.

@Zambrella and I will be leaving you some useful tips and suggestions as you push the new code. Then after the reviews, we'll merge your PR.

Looking forward to your contributions!

**Review by slovnicki — APPROVED** [review]
LGTM :)
thanks for the PR @thgehr

**Pull request merged**
